### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by rainy112233** [yasin-esfandiari/2D-Object-Detection-Using-DETR-on-JRDB#1]
Hello, teacher. I met some problems when learning your document. May I ask for your advice?
When running the main.py, I do not know that the training loss is particularly high, so could you please let me refer to your checkpoint.
Thank you for checking my question, and I would really appreciate your help.

**Comment by yasin-esfandiari** [comment]
Hi. I added the checkpoint. Hope it can help.

**Comment by rainy112233** [comment]
I am very glad to receive your reply. Thank you very much for your help.wish you a happy life！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yasin-esfandiari/2D-Object-Detection-Using-DETR-on-JRDB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 晚上11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yasin-esfandiari/2D-Object-Detection-Using-DETR-on-JRDB] Ask for help (Issue #1)





 
Hi. I added the checkpoint. Hope it can help.
